"""Transcript fetching module with youtube-transcript-api primary and yt-dlp fallback."""

from __future__ import annotations

import json
import logging
import re
import subprocess
import tempfile
from pathlib import Path

from pydantic import BaseModel, Field
from youtube_transcript_api import YouTubeTranscriptApi

logger = logging.getLogger(__name__)


class TranscriptResult(BaseModel):
    """Result of a transcript fetch operation."""

    text_with_timestamps: list[dict] = Field(
        description="List of dicts with 'start', 'duration', and 'text' keys."
    )
    full_text: str = Field(description="Concatenated plain text of the transcript.")
    language: str | None = Field(default=None, description="Language code of the transcript.")
    is_auto_generated: bool = Field(
        default=False, description="Whether the transcript was auto-generated by YouTube."
    )
    source: str = Field(
        default="api", description="Source of the transcript: 'api' or 'yt-dlp'."
    )


def clean_transcript(raw_text: str) -> str:
    """Remove noise tags and normalize whitespace.

    Removes [Music], [Applause], [Laughter] and similar bracketed tags,
    then collapses multiple whitespace characters into single spaces.
    """
    # Remove common bracketed noise tags (case-insensitive)
    cleaned = re.sub(r"\[(?:Music|Applause|Laughter)\]", "", raw_text, flags=re.IGNORECASE)
    # Collapse multiple whitespace into single space and strip
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    return cleaned


def _scrapedo_proxy() -> str | None:
    """Build a scrape.do proxy URL from settings, or None if not configured."""
    from youtube_brain.config.settings import get_settings

    token = get_settings().scrapedo_token
    return f"http://{token}:@proxy.scrape.do:8080" if token else None


def _cookies_browser() -> str | None:
    """Browser to read YouTube cookies from, or None if not configured."""
    from youtube_brain.config.settings import get_settings

    return get_settings().ytdlp_cookies_browser or None


def _cookies_file() -> str | None:
    """Path to a Netscape cookies.txt, or None if not configured/missing."""
    from youtube_brain.config.settings import get_settings

    path = get_settings().ytdlp_cookies_file
    return path if path and Path(path).exists() else None


async def fetch_transcript(video_id: str) -> TranscriptResult | None:
    """Fetch transcript for a YouTube video.

    Strategy order (most resilient first, configured via settings):
      1. Authenticated direct fetch using browser cookies (free; usually
         bypasses rate limits). Requires the browser to be closed on Windows.
      2. scrape.do rotating-IP proxy (paid per request). NEVER combined with
         cookies — the proxy intercepts TLS and must not see account cookies.
      3. youtube-transcript-api direct.
      4. Plain yt-dlp direct.
    Returns None if all methods fail.
    """
    cookies_file = _cookies_file()
    if cookies_file:
        result = _try_yt_dlp(video_id, cookies_file=cookies_file)
        if result is not None:
            return result
        logger.info("cookies-file fetch failed for %s, trying next", video_id)

    cookies = _cookies_browser()
    if cookies:
        result = _try_yt_dlp(video_id, cookies_browser=cookies)
        if result is not None:
            return result
        logger.info("cookie-authenticated fetch failed for %s, trying next", video_id)

    proxy = _scrapedo_proxy()
    if proxy:
        result = _try_yt_dlp(video_id, proxy=proxy)
        if result is not None:
            return result
        logger.info("scrape.do-proxied fetch failed for %s, trying direct", video_id)

    result = _try_youtube_transcript_api(video_id)
    if result is not None:
        return result

    logger.info("youtube-transcript-api failed for %s, trying yt-dlp fallback", video_id)
    result = _try_yt_dlp(video_id)
    if result is not None:
        return result

    logger.warning("All transcript fetch methods failed for video %s", video_id)
    return None


def _try_youtube_transcript_api(video_id: str) -> TranscriptResult | None:
    """Fetch transcript using youtube-transcript-api.

    Prefers manually created captions over auto-generated ones.
    """
    try:
        ytt_api = YouTubeTranscriptApi()
        transcript_list = ytt_api.list(video_id)

        # Try manually created transcript first, then fall back to auto-generated
        transcript = None
        is_generated = False

        try:
            transcript = transcript_list.find_manually_created_transcript(["en"])
            is_generated = False
        except Exception:
            try:
                transcript = transcript_list.find_generated_transcript(["en"])
                is_generated = True
            except Exception:
                # Last resort: try any available transcript
                try:
                    transcript = transcript_list.find_transcript(["en"])
                    is_generated = transcript.is_generated
                except Exception:
                    logger.debug("No English transcript found for %s", video_id)
                    return None

        fetched = transcript.fetch()

        # Convert to list of dicts using to_raw_data()
        segments = fetched.to_raw_data()

        full_text = " ".join(s["text"] for s in segments)

        return TranscriptResult(
            text_with_timestamps=segments,
            full_text=clean_transcript(full_text),
            language=transcript.language_code,
            is_auto_generated=is_generated,
            source="api",
        )

    except Exception:
        logger.debug("youtube-transcript-api failed for %s", video_id, exc_info=True)
        return None


def _try_yt_dlp(
    video_id: str,
    proxy: str | None = None,
    cookies_browser: str | None = None,
    cookies_file: str | None = None,
) -> TranscriptResult | None:
    """Fetch transcript using a yt-dlp subprocess.

    Runs yt-dlp with --write-auto-subs --skip-download to extract subtitles
    in JSON3 format, then parses the result. When *proxy* is set, routes
    through it (e.g. scrape.do) and disables TLS verification, since proxy
    services intercept TLS. When *cookies_browser* is set, authenticates with
    that browser's cookies. The two are mutually exclusive — account cookies
    must never transit an intercepting proxy.
    """
    if proxy and (cookies_browser or cookies_file):
        raise ValueError("proxy and cookies are mutually exclusive")

    url = f"https://www.youtube.com/watch?v={video_id}"

    with tempfile.TemporaryDirectory() as tmpdir:
        output_template = str(Path(tmpdir) / "%(id)s")

        cmd = [
            "yt-dlp",
            "--write-auto-subs",
            "--write-subs",
            "--skip-download",
            "--sub-lang", "en",
            "--sub-format", "json3",
            "--output", output_template,
        ]
        if proxy:
            cmd += ["--proxy", proxy, "--no-check-certificates"]
        if cookies_file:
            cmd += ["--cookies", cookies_file]
        elif cookies_browser:
            cmd += ["--cookies-from-browser", cookies_browser]
        cmd.append(url)

        try:
            subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=120 if proxy else 60,
                check=False,
            )

            # Look for the subtitle file (could be .en.json3)
            tmppath = Path(tmpdir)
            sub_files = list(tmppath.glob(f"{video_id}*.json3"))

            if not sub_files:
                logger.debug("No subtitle file produced by yt-dlp for %s", video_id)
                return None

            sub_file = sub_files[0]
            is_auto = ".auto." in sub_file.name or "auto" in sub_file.name.lower()

            with open(sub_file, encoding="utf-8") as f:
                data = json.load(f)

            segments = _parse_json3(data)
            if not segments:
                return None

            full_text = " ".join(s["text"] for s in segments)

            return TranscriptResult(
                text_with_timestamps=segments,
                full_text=clean_transcript(full_text),
                language="en",
                is_auto_generated=is_auto,
                source="yt-dlp",
            )

        except subprocess.TimeoutExpired:
            logger.debug("yt-dlp timed out for %s", video_id)
            return None
        except Exception:
            logger.debug("yt-dlp failed for %s", video_id, exc_info=True)
            return None


def _parse_json3(data: dict) -> list[dict]:
    """Parse YouTube JSON3 subtitle format into a list of segment dicts."""
    segments: list[dict] = []
    events = data.get("events", [])

    for event in events:
        # Skip events without text segments
        segs = event.get("segs")
        if not segs:
            continue

        text = "".join(seg.get("utf8", "") for seg in segs).strip()
        if not text or text == "\n":
            continue

        start_ms = event.get("tStartMs", 0)
        duration_ms = event.get("dDurationMs", 0)

        segments.append({
            "start": start_ms / 1000.0,
            "duration": duration_ms / 1000.0,
            "text": text,
        })

    return segments
